export enum SHIP_MODEL {
  ALPHA_BLUE = 'alpha_blue',
  ARROW_BLUE = 'arrow_blue',
  BURAN_BLUE = 'buran_blue',
  CYCLONE_BLUE = 'cyclone_blue',
  RAVEN_BLUE = 'raven_blue',
  REX_BLUE = 'rex_blue',
  WOLFRAM_BLUE = 'wolfram_blue',

  ALPHA_GREY = 'alpha_grey',
  ARROW_GREY = 'arrow_grey',
  BURAN_GREY = 'buran_grey',
  CYCLONE_GREY = 'cyclone_grey',
  RAVEN_GREY = 'raven_grey',
  REX_GREY = 'rex_grey',
  WOLFRAM_GREY = 'wolfram_grey',

  ALPHA_RED = 'alpha_red',
  ARROW_RED = 'arrow_red',
  BURAN_RED = 'buran_red',
  CYCLONE_RED = 'cyclone_red',
  RAVEN_RED = 'raven_red',
  REX_RED = 'rex_red',
  WOLFRAM_RED = 'wolfram_red',

  ALPHA_WHITE = 'alpha_white',
  ARROW_WHITE = 'arrow_white',
  BURAN_WHITE = 'buran_white',
  CYCLONE_WHITE = 'cyclone_white',
  RAVEN_WHITE = 'raven_white',
  REX_WHITE = 'rex_white',
  WOLFRAM_WHITE = 'wolfram_white',

  ALPHA_YELLOW = 'alpha_yellow',
  ARROW_YELLOW = 'arrow_yellow',
  BURAN_YELLOW = 'buran_yellow',
  CYCLONE_YELLOW = 'cyclone_yellow',
  RAVEN_YELLOW = 'raven_yellow',
  REX_YELLOW = 'rex_yellow',
  WOLFRAM_YELLOW = 'wolfram_yellow',
}
